use crate::report::{Alert, ScanReport};
use maud::{html, Markup, DOCTYPE};

/// Generate an HTML report from scan results
pub fn generate_html_report(report: &ScanReport) -> String {
    let markup = html! {
        (DOCTYPE)
        html lang="en" {
            head {
                meta charset="UTF-8";
                meta name="viewport" content="width=device-width, initial-scale=1.0";
                title { "Security Scan Report - " (report.target) }
                style {
                    (css_styles())
                }
            }
            body {
                div class="container" {
                    header class="header" {
                        h1 { "Security Scan Report" }
                        p class="timestamp" { "Generated: " (report.timestamp) }
                    }

                    section class="target-info" {
                        h2 { "Target Information" }
                        p { strong { "URL: " } (report.target) }
                        p { strong { "Scan Date: " } (report.timestamp) }
                    }

                    section class="summary" {
                        h2 { "Vulnerability Summary" }
                        div class="summary-grid" {
                            div class="summary-card critical" {
                                div class="summary-number" { (report.critical_count()) }
                                div class="summary-label" { "Critical" }
                            }
                            div class="summary-card high" {
                                div class="summary-number" { (report.high_count()) }
                                div class="summary-label" { "High" }
                            }
                            div class="summary-card medium" {
                                div class="summary-number" { (report.medium_count()) }
                                div class="summary-label" { "Medium" }
                            }
                            div class="summary-card low" {
                                div class="summary-number" { (report.low_count()) }
                                div class="summary-label" { "Low" }
                            }
                            div class="summary-card total" {
                                div class="summary-number" { (report.vulnerability_count()) }
                                div class="summary-label" { "Total Issues" }
                            }
                        }
                    }

                    section class="vulnerabilities" {
                        h2 { "Detailed Findings" }
                        @if report.alerts.is_empty() {
                            p class="no-issues" { "✓ No vulnerabilities found!" }
                        } @else {
                            div class="alerts" {
                                @for alert in &report.alerts {
                                    (render_alert(alert))
                                }
                            }
                        }
                    }

                    footer class="footer" {
                        p { "Generated by Arete Security Scanner" }
                    }
                }
            }
        }
    };

    markup.into_string()
}

/// Render a single vulnerability alert
fn render_alert(alert: &Alert) -> Markup {
    let risk_class = get_risk_class(&alert.riskcode);
    let confidence_class = get_confidence_class(&alert.confidence);
    let risk_label = get_risk_label(&alert.riskcode);
    let confidence_label = get_confidence_label(&alert.confidence);

    html! {
        div class=(format!("alert alert-{}", risk_class)) {
            div class="alert-header" {
                h3 class="alert-title" { (alert.alert) }
                div class="alert-badges" {
                    span class=(format!("badge risk-{}", risk_class)) { (risk_label) }
                    span class=(format!("badge confidence-{}", confidence_class)) { 
                        "Confidence: " (confidence_label)
                    }
                }
            }

            @if let Some(description) = &alert.description {
                div class="alert-description" {
                    p { (description) }
                }
            }

            div class="alert-details" {
                div class="detail-group" {
                    strong { "Affected URL:" }
                    p { code { (alert.url) } }
                }

                div class="detail-group" {
                    strong { "Plugin ID:" }
                    p { (alert.pluginid) }
                }

                @if !alert.instances.is_empty() {
                    div class="detail-group" {
                        strong { "Instances:" }
                        table class="instances-table" {
                            thead {
                                tr {
                                    th { "URI" }
                                    th { "Method" }
                                    @if alert.instances.iter().any(|i| i.param.is_some()) {
                                        th { "Parameter" }
                                    }
                                    @if alert.instances.iter().any(|i| i.evidence.is_some()) {
                                        th { "Evidence" }
                                    }
                                }
                            }
                            tbody {
                                @for instance in &alert.instances {
                                    tr {
                                        td { code { (instance.uri) } }
                                        td { (instance.method) }
                                        @if alert.instances.iter().any(|i| i.param.is_some()) {
                                            td {
                                                @if let Some(param) = &instance.param {
                                                    (param)
                                                }
                                            }
                                        }
                                        @if alert.instances.iter().any(|i| i.evidence.is_some()) {
                                            td {
                                                @if let Some(evidence) = &instance.evidence {
                                                    code { (evidence) }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Get CSS class for risk level
fn get_risk_class(riskcode: &str) -> &'static str {
    match riskcode {
        "3" => "critical",
        "2" => "high",
        "1" => "medium",
        _ => "low",
    }
}

/// Get CSS class for confidence level
fn get_confidence_class(confidence: &str) -> &'static str {
    match confidence {
        "2" => "high",
        "1" => "medium",
        _ => "low",
    }
}

/// Get human-readable risk label
fn get_risk_label(riskcode: &str) -> &'static str {
    match riskcode {
        "3" => "CRITICAL",
        "2" => "HIGH",
        "1" => "MEDIUM",
        _ => "LOW",
    }
}

/// Get human-readable confidence label
fn get_confidence_label(confidence: &str) -> &'static str {
    match confidence {
        "2" => "High",
        "1" => "Medium",
        _ => "Low",
    }
}

/// Embedded CSS styles for the HTML report
fn css_styles() -> &'static str {
    r#"
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 8px;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
    overflow: hidden;
}

.header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 40px 30px;
    text-align: center;
}

.header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
}

.header .timestamp {
    font-size: 0.95em;
    opacity: 0.9;
}

section {
    padding: 30px;
    border-bottom: 1px solid #eee;
}

section:last-child {
    border-bottom: none;
}

h2 {
    font-size: 1.8em;
    margin-bottom: 20px;
    color: #2c3e50;
}

.target-info {
    background: #f8f9fa;
}

.target-info p {
    margin: 10px 0;
    font-size: 1.05em;
}

.target-info strong {
    color: #667eea;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.summary-card {
    padding: 20px;
    border-radius: 8px;
    text-align: center;
    border: 2px solid transparent;
    transition: transform 0.2s;
}

.summary-card:hover {
    transform: translateY(-5px);
}

.summary-card.critical {
    background: #fee;
    border-color: #f55;
    color: #c00;
}

.summary-card.high {
    background: #ffd6d6;
    border-color: #ff6b6b;
    color: #c92a2a;
}

.summary-card.medium {
    background: #fff3cd;
    border-color: #ffc107;
    color: #856404;
}

.summary-card.low {
    background: #d1ecf1;
    border-color: #17a2b8;
    color: #0c5460;
}

.summary-card.total {
    background: #e7f3ff;
    border-color: #667eea;
    color: #667eea;
}

.summary-number {
    font-size: 2.5em;
    font-weight: bold;
}

.summary-label {
    font-size: 0.9em;
    margin-top: 8px;
    text-transform: uppercase;
    font-weight: 600;
}

.no-issues {
    background: #d4edda;
    color: #155724;
    padding: 15px 20px;
    border-radius: 5px;
    border: 1px solid #c3e6cb;
}

.alerts {
    display: flex;
    flex-direction: column;
    gap: 20px;
}

.alert {
    border-left: 5px solid;
    padding: 20px;
    background: #f9f9f9;
    border-radius: 5px;
    transition: box-shadow 0.2s;
}

.alert:hover {
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.alert-critical {
    border-left-color: #f55;
    background: #fee;
}

.alert-high {
    border-left-color: #ff6b6b;
    background: #ffd6d6;
}

.alert-medium {
    border-left-color: #ffc107;
    background: #fff3cd;
}

.alert-low {
    border-left-color: #17a2b8;
    background: #d1ecf1;
}

.alert-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 15px;
    gap: 20px;
}

.alert-title {
    font-size: 1.3em;
    margin: 0;
    flex: 1;
}

.alert-badges {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
    justify-content: flex-end;
}

.badge {
    padding: 6px 12px;
    border-radius: 20px;
    font-size: 0.85em;
    font-weight: 600;
    white-space: nowrap;
}

.badge.risk-critical {
    background: #f55;
    color: white;
}

.badge.risk-high {
    background: #ff6b6b;
    color: white;
}

.badge.risk-medium {
    background: #ffc107;
    color: #333;
}

.badge.risk-low {
    background: #17a2b8;
    color: white;
}

.badge.confidence-high {
    background: #28a745;
    color: white;
}

.badge.confidence-medium {
    background: #ffc107;
    color: #333;
}

.badge.confidence-low {
    background: #6c757d;
    color: white;
}

.alert-description {
    margin-bottom: 15px;
    padding: 10px;
    background: white;
    border-radius: 3px;
}

.alert-description p {
    margin: 0;
}

.alert-details {
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.detail-group {
    background: white;
    padding: 12px;
    border-radius: 3px;
}

.detail-group strong {
    color: #667eea;
    display: block;
    margin-bottom: 8px;
}

.detail-group p {
    margin: 0;
}

.detail-group code {
    background: #f5f5f5;
    padding: 4px 8px;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    font-size: 0.9em;
    word-break: break-all;
}

.instances-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.95em;
}

.instances-table thead {
    background: #667eea;
    color: white;
}

.instances-table th,
.instances-table td {
    padding: 10px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.instances-table tbody tr:nth-child(even) {
    background: #f9f9f9;
}

.instances-table tbody tr:hover {
    background: #efefef;
}

.instances-table code {
    background: #f5f5f5;
    padding: 3px 6px;
    border-radius: 3px;
    font-size: 0.9em;
}

.footer {
    background: #f8f9fa;
    padding: 20px;
    text-align: center;
    color: #666;
    font-size: 0.9em;
}

@media (max-width: 768px) {
    .header {
        padding: 20px;
    }

    .header h1 {
        font-size: 1.8em;
    }

    section {
        padding: 20px;
    }

    .summary-grid {
        grid-template-columns: 1fr 1fr;
    }

    .alert-header {
        flex-direction: column;
        align-items: flex-start;
    }

    .alert-badges {
        justify-content: flex-start;
    }

    .instances-table {
        font-size: 0.85em;
    }

    .instances-table th,
    .instances-table td {
        padding: 8px;
    }
}
    "#
}
